import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { FloatingNav } from "@/components/nava";
import CookiesPopup from "@/components/ui/Cookie";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <div>
        <FloatingNav/>
        <CookiesPopup/>
        </div>
        
        {children}</body>
    </html>
  );
}
